import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/navbar/Navbar'
import Footer from '@/component/footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BOG',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
         {/* <h1>Main layout es gamochndeba yvelgan</h1>  */}
  
      <Navbar/>
       
        {children}     

     <Footer/> 


        </body>
    </html>
  )
}
